---
- block:
    - name: Ensure pip and venv is installed
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      loop:
        - python3-pip
        - python3-venv

    - name: Ensure the virtual environment exists
      ansible.builtin.pip:
        name: "{{ venv_modules }}"
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: "python3 -m venv"

    - name: Wait for all Longhorn volumes to be healthy
      ansible.builtin.script: files/check_longhorn.py --kubectl_path {{ rke2_data_path }}/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml
      args:
        executable: "{{ venv_python }}"
      register: all_longhorn_vol_healthy
      failed_when: all_longhorn_vol_healthy.stdout.strip() != ""
      changed_when: false
      until: all_longhorn_vol_healthy.stdout.strip() == ""
      retries: 120
      delay: 15
  vars:
    venv_modules:
      - psutil==6.0.0
      - requests
    venv_dir: /tmp/k8s_rolling_restart_venv
    venv_python: "{{ venv_dir }}/bin/python3"
  always:
    - name: Ensure the virtual environment is deleted
      ansible.builtin.file:
        path: "{{ venv_dir }}"
        state: absent

    - name: Longhorn check error
      ansible.builtin.fail:
        msg: To prevent data loss, the play will be terminated.